name: Merge Crowdin Pull Requests

env:
  MERGE_LABELS: ""
  MERGE_METHOD: "squash"
  MERGE_COMMIT_MESSAGE: "Crowdin Sync #{pullRequest.number}"

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  status: {}
jobs:
  automerge:
    #check to make sure the pr is related to Crowdin and the pr creator is Cryotheus
    if: ${{ github.event.pull_request.head.ref == 'l10n_main' && github.actor_id == 14439112 }}
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
