name: Merge Crowdin Pull Requests

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  status: {}
jobs:
  automerge:
    #check to make sure the pr is related to Crowdin and the pr creator is Cryotheus
    if: ${{ contains(github.event.head_commit.message, 'Crowdin') && github.actor_id == '14439112' }}
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
